#!/usr/bin/env bash
# installs nginx

apt-get update -y
apt-get install nginx -y

# Configure Nginx
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location = / {
        try_files /index.html =404;
    }
}
EOF

cat > /var/www/html/index.html <<EOF
Hello World!
EOF

service nginx restart
