#!/usr/bin/env bash
# set up a custom header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "47i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo service nginx start
