#!/usr/bin/env bash
# set up a custom header
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 531161-web-01 54.208.177.196:80 check\n\tserver 531161-web-02 54.54.209.3.37:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
