#!/usr/bin/env bash
# a comment explaining what it is doing
i=1
while ((i < 101)); do
  if ((i % 3 == 0 && i % 5 == 0)); then
    echo "FizzBuzz"
  elif ((i % 3 == 0)); then
    echo "Fizz"
  elif ((i % 5 == 0)); then
    echo "Buzz"
  else
    echo "$i"
  fi
  ((i = i + 1))
done
