#!/usr/bin/env bash
# a comment explaining what it is doing
while IFS=: read -r username password userid groupid userinfo homedirectory command; do
    echo "The user $username is part of the $groupid gang, lives in $homedirectory and rides $command. $userid's place is protected by the passcode $password, more info about the user here: $userinfo"
done < /etc/passwd
