#!/usr/bin/env bash
# a comment explaining what it is doing
i=1
while ((i < 21)); do
  if ((i == 4)); then
    echo $i
    echo "bad luck from China"
  elif ((i == 9)); then
    echo $i
    echo "bad luck from Japan"
  elif ((i == 17)); then
    echo $i
    echo "bad luck from Italy"
  else
    echo $i
  fi
  ((i = i + 1))
done
