#!/usr/bin/env bash
# a comment explaining what it is doing
i=1
while ((i < 21)); do
  case $i in
    4)
      echo $i
      echo "bad luck from China"
      ;;
    9)
      echo $i
      echo "bad luck from Japan"
      ;;
    17)
      echo $i
      echo "bad luck from Italy"
      ;;
    *)
      echo $i
      ;;
  esac
  ((i = i + 1))
done
