#!/usr/bin/env bash
# a comment explaining what it is doing
j=12
k=59
i=0
minutes=60
seconds=60
while ((i < j)); do
  echo "Hour: $i"
  m=1
  while ((m < minutes)); do
    echo $m
    ((m = m + 1))
  done
  ((i = i + 1))
done
