#!/usr/bin/env bash
# a comment explaining what it is doing
j=12
i=0
minutes=60
((j = j + 1))
while ((i < j)); do
  echo "Hour: $i"
  m=1
  while ((m < minutes)); do
    echo $m
    ((m = m + 1))
  done
  ((i = i + 1))
done
