#!/usr/bin/env bash
# a comment explaining what it is doing
cp /etc/hosts /etc/new_hosts
echo "8.8.8.8 facebook.com" >> /etc/new_hosts
sed -i "s/127.0.0.1/127.0.0.2/" /etc/new_hosts
cp -f /etc/new_hosts /etc/hosts
