#!/usr/bin/env bash
# reloads Gunicorn

# Gunicorn process IDs
gunicorn_pids=$(pgrep gunicorn)

if [ -z "$gunicorn_pids" ]; then
    echo "No Gunicorn processes found."
    exit 1
fi

# Stop old workers
echo "Stopping old workers gracefully..."
for pid in $gunicorn_pids; do
    kill -HUP "$pid"
done

# waiting
echo "Waiting for old workers to finish processing..."
sleep 5

echo "Graceful reload complete"
